name: twitch-cycling-jawn
version: '0.1'
summary: A package for streaming bicycle rides to Twitch
description: |
  A snap to use the Raspberry Pi camera and a GPS hat to stream bicycle
  rides to Twitch with live info about speed, power, and heart rate

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: [armhf, arm64]
    run-on: [armhf, arm64]

apps:
  stream-with-data:
    daemon: simple
    command: bin/sensor_data
    plugs:
      - serial-port
      - opengl
      - camera
      - network
      - network-bind
      - bluez
  configjawn:
    command: bin/sensor_config
    plugs:
      - bluez

parts:
  stream-with-data:
    plugin: python
    source: .
    build-packages:
      - python3-wheel
      - python3-dev
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    python-packages:
      - adafruit-circuitpython-gps
      - board
      - bleak
      - pygeodesy
    stage-packages:
      - ffmpeg
      - python3-wheel
      - libpulse0
      - fonts-ubuntu
    stage-snaps:
      - bluez
    override-build: |
      snapcraftctl build
      cp $SNAPCRAFT_PROJECT_DIR/twitch-stream $SNAPCRAFT_PART_INSTALL/bin
